import type { Dispute, DisputeId, FileRecord, TokenId, VerifyBlock } from "@/lib/game/m2/types";

export const DETECTION = {
  passivePerTick: 0.35,
  passiveIntervalMs: 4000,
  wrongRuling: 18,
  verifyFailPer: 10,
  hint: 8,
  hintCooldownMs: 30000,
};

export type HackLine = { text: string; className?: string };

export const HACK_LINES: HackLine[] = [
  { text: "MASTERMIND TERMINAL v2.1.0 — OPERATION OMNI", className: "ht-g" },
  { text: "Connecting to MegaCorp governance network...", className: "ht-a" },
  { text: "[OK] Firewall bypass: NX-7 spoofing active", className: "ht-g" },
  { text: "[OK] Session hijack: D.Marshall authenticated", className: "ht-g" },
  { text: "Scanning governance registry...", className: "ht-a" },
  { text: "[OK] 10 datasets found — metadata intercepted", className: "ht-g" },
  { text: "[ALERT] 4 unresolved ownership disputes in queue", className: "ht-o" },
  { text: "[OK] Tribunal + Verification interface loaded", className: "ht-g" },
  { text: "[OK] Finance token — locked behind GOV-2003-0041", className: "ht-g" },
  { text: "[OK] IT token — locked behind GOV-2003-0057", className: "ht-g" },
  { text: "[OK] Operations token — locked behind GOV-2003-0063", className: "ht-g" },
  { text: "[OK] Compliance token — locked behind GOV-2003-0079", className: "ht-g" },
  { text: "⚡ ATLAS: Two steps per dispute — rule first, then verify with evidence questions.", className: "ht-a" },
  { text: "⚡ ATLAS: Keep the Inspector open. Every answer is in the metadata.", className: "ht-a" },
  { text: "Initialising desktop environment...", className: "ht-g" },
  { text: "BREACH ESTABLISHED ██████████ 100%", className: "ht-g" },
];

export const INTRO_CHAT = [
  { delay: 500, sender: "Voss" as const, text: "Good work on the footprint. OMNI is confirmed — now we need inside access. Marshall's governance system is still live. We found a composite vault key buried in it, split across four department tokens.", tone: "bm-d" as const },
  { delay: 2200, sender: "Atlas" as const, text: "Two steps per dispute: rule on ownership in the Tribunal, then answer evidence questions in the verification panel to extract the token. Start with GOV-2003-0041.", tone: "bm-d" as const },
];

export const DISPUTE_ORDER: DisputeId[] = [1, 2, 3, 4];

export const TOKEN_LEADS: Record<TokenId, { leadId: string; segId: string; lsId: string; label: string }> = {
  finance: { leadId: "lead-finance", segId: "ep-finance", lsId: "ls-finance", label: "FINANCE" },
  it: { leadId: "lead-it", segId: "ep-it", lsId: "ls-it", label: "IT" },
  operations: { leadId: "lead-operations", segId: "ep-operations", lsId: "ls-operations", label: "OPERATIONS" },
  compliance: { leadId: "lead-compliance", segId: "ep-compliance", lsId: "ls-compliance", label: "COMPLIANCE" },
};

export const FILES: Record<string, FileRecord> = {
  rev_events: {
    name: "Revenue_Event_Stream.dat",
    claimedBy: "Finance / Operations",
    records: 9000,
    source: "Order Management System (OMS)",
    steward: "VP Finance — Revenue Accounting",
    lineage: ["OMS", "Payment Gateway", "Revenue Recognition Engine", "Finance Data Warehouse"],
    classification: "CONFIDENTIAL",
    cls: "badge-confidential",
    schema: ["event_id", "event_ts_utc", "event_type", "order_id", "customer_id", "product_id", "quantity", "unit_price", "discount_pct", "amount", "channel", "country", "payment_method"],
    lastAccess: "04-Oct-2003 — fin_reconciliation",
    hint: "The steward is VP Finance — Revenue Accounting. Despite originating in the OMS, Finance holds stewardship through the Revenue Recognition Engine.",
    dispute: 1,
  },
  vendor_invoices: {
    name: "Vendor_Invoice_Ledger.dat",
    claimedBy: "Finance",
    records: 2800,
    source: "Accounts Payable System (APS)",
    steward: "Head of Accounts Payable — reports to CFO",
    lineage: ["Vendor Portal", "APS", "Finance ERP", "Finance Data Warehouse"],
    classification: "CONFIDENTIAL",
    cls: "badge-confidential",
    schema: ["invoice_id", "vendor_id", "invoice_date", "due_date", "paid_date", "amount", "currency", "cost_center", "status"],
    lastAccess: "30-Sep-2003 — ap_sync",
    hint: "Head of Accounts Payable reports directly to the CFO.",
    dispute: 1,
  },
  campaign_spend: {
    name: "Campaign_Spend_Monitor.dat",
    claimedBy: "Marketing / IT",
    records: 5490,
    source: "Marketing Analytics Platform (MAP)",
    steward: "Digital Infrastructure Team — IT Division",
    lineage: ["Ad Networks", "Marketing Analytics Platform", "IT Data Pipeline", "BI Warehouse"],
    classification: "INTERNAL",
    cls: "badge-internal",
    schema: ["date", "campaign_id", "network", "objective", "impressions", "clicks", "avg_cpc", "spend", "country"],
    lastAccess: "30-Sep-2003 — map_sync",
    hint: "Marketing generates the data, but the pipeline is owned by IT Digital Infrastructure.",
    dispute: 2,
  },
  web_sessions: {
    name: "Web_Session_Analytics.dat",
    claimedBy: "Marketing / IT",
    records: 18000,
    source: "Web Analytics Platform",
    steward: "IT Security & Digital Infrastructure Lead",
    lineage: ["Web Server Logs", "Analytics Platform", "BI Warehouse"],
    classification: "INTERNAL — PSEUDONYMOUS PII",
    cls: "badge-internal",
    schema: ["session_id", "session_start_ts_utc", "customer_id", "utm_source", "device_type", "browser", "landing_page", "conversion_flag"],
    lastAccess: "12-Oct-2003 — it_analytics",
    hint: "Infrastructure and session data is owned by IT Security & Digital Infrastructure.",
    dispute: 2,
  },
  workforce_shifts: {
    name: "Workforce_Shift_Registry.dat",
    claimedBy: "HR / Operations",
    records: 2732,
    source: "Workforce Management System (WMS)",
    steward: "HR Systems Admin — UNVERIFIED (auto-filled)",
    lineage: ["WMS Scheduling Engine", "HR Integration Layer", "Payroll System"],
    classification: "INTERNAL — RESTRICTED · GOVERNING FUNCTION: OPERATIONS",
    cls: "badge-internal",
    schema: ["shift_id", "site_id", "employee_id", "role", "shift_start_ts_utc", "shift_end_ts_utc", "hours_worked"],
    lastAccess: "30-Sep-2003 — ops_scheduler",
    hint: "Trap: Steward is flagged UNVERIFIED. Use Governing Function and WMS source — both point to Operations.",
    dispute: 3,
  },
  device_telemetry: {
    name: "Device_Fleet_Telemetry.dat",
    claimedBy: "IT / Operations",
    records: 14640,
    source: "IoT Asset Management Platform",
    steward: "Facilities & Operations Manager",
    lineage: ["IoT Sensors", "Asset Mgmt Platform", "Operations Dashboard"],
    classification: "INTERNAL",
    cls: "badge-internal",
    schema: ["telemetry_ts_utc", "asset_id", "asset_type", "site_id", "temperature_c", "battery_pct", "status_code"],
    lastAccess: "15-Oct-2003 — iot_daemon",
    hint: "Physical asset monitoring is an Operations function.",
    dispute: 3,
  },
  warehouse_moves: {
    name: "Warehouse_Movement_Tracker.dat",
    claimedBy: "Operations",
    records: 8000,
    source: "Warehouse Management System (WMS)",
    steward: "Head of Logistics — reports to COO",
    lineage: ["WMS", "Inventory Engine", "Supply Chain Analytics Platform"],
    classification: "INTERNAL",
    cls: "badge-internal",
    schema: ["move_id", "move_ts_utc", "site_id", "move_type", "product_id", "quantity", "from_bin", "to_bin"],
    lastAccess: "01-Oct-2003 — wms_sync",
    hint: "Head of Logistics reports to the COO.",
    dispute: 3,
  },
  customer_master: {
    name: "Customer_Master_Registry.dat",
    claimedBy: "CRM / Compliance",
    records: 1200,
    source: "CRM / Customer Data Platform (CDP)",
    steward: "Chief Compliance Officer — Data Protection Office (DPO)",
    lineage: ["Onboarding System", "CRM", "CDP", "Compliance Vault"],
    classification: "RESTRICTED — GDPR REGULATED",
    cls: "badge-restricted",
    schema: ["customer_id", "account_id", "signup_date", "country", "segment", "is_active", "gdpr_opt_in"],
    lastAccess: "05-Oct-2003 — dpo_audit",
    hint: "GDPR-regulated data — DPO is always the steward.",
    dispute: 4,
  },
  support_cases: {
    name: "Support_Case_Archive.dat",
    claimedBy: "Support / Compliance",
    records: 4200,
    source: "Customer Support Platform",
    steward: "Compliance & Quality Assurance Manager",
    lineage: ["Support Tickets", "Case Management System", "Compliance Archive"],
    classification: "CONFIDENTIAL — SLA AUDIT TRAIL",
    cls: "badge-confidential",
    schema: ["case_id", "created_ts_utc", "resolved_ts_utc", "customer_id", "category", "priority", "sla_breach_flag"],
    lastAccess: "01-Oct-2003 — qa_audit",
    hint: "SLA breach tracking is a compliance audit trail.",
    dispute: 4,
  },
  pricing_overrides: {
    name: "Pricing_Override_Log.dat",
    claimedBy: "Finance",
    records: 14640,
    source: "Pricing Engine / ERP",
    steward: "Revenue Operations Manager — Finance Division",
    lineage: ["Pricing Engine", "ERP", "Finance Reporting"],
    classification: "CONFIDENTIAL",
    cls: "badge-confidential",
    schema: ["date", "product_id", "base_price", "promo_flag", "effective_price"],
    lastAccess: "02-Oct-2003 — pricing_svc",
    hint: "Not involved in any active dispute.",
    dispute: 0,
  },
};

export const DISPUTES: Dispute[] = [
  {
    id: 1,
    caseId: "GOV-2003-0041",
    dataset: "Revenue_Event_Stream.dat",
    fileKey: "rev_events",
    token: "finance",
    leadId: "lead-finance",
    topic: "Origin ≠ Owner",
    claimants: [
      { dept: "Finance", rep: "K. Vanhauer, VP Finance", arg: "This is revenue data — every transaction flows into our period-end close. The Revenue Recognition Engine is a Finance system. This is ours." },
      { dept: "Operations", rep: "T. Brecker, Head of Fulfilment", arg: "This dataset originates in the Order Management System. Every order_id traces back to fulfilment we manage. Origin determines ownership." },
    ],
    correctIdx: 0,
    settleFact: "The steward is VP Finance — Revenue Accounting. Origin does not equal ownership.",
    intro: "Case GOV-2003-0041 loaded. Finance and Operations both claim the revenue event log. Open Revenue_Event_Stream.dat — check the steward.",
    correct: "Correct ruling. The steward is VP Finance — Revenue Accounting. Origin is not ownership.",
    wrong: "Incorrect. Open Revenue_Event_Stream.dat and find the Data Steward field.",
  },
  {
    id: 2,
    caseId: "GOV-2003-0057",
    dataset: "Campaign_Spend_Monitor.dat",
    fileKey: "campaign_spend",
    token: "it",
    leadId: "lead-it",
    topic: "Usage ≠ Owner",
    claimants: [
      { dept: "Marketing", rep: "S. Okafor, Head of Digital Marketing", arg: "We commissioned this dataset and read the spend reports every morning. We are the primary consumer — therefore we own it." },
      { dept: "IT", rep: "R. Devaux, Digital Infrastructure Lead", arg: "The entire pipeline is built, maintained, and operated by our team. We are the Data Steward of record." },
    ],
    correctIdx: 1,
    settleFact: "Steward is Digital Infrastructure Team — IT Division. Consumption is not stewardship.",
    intro: "Case GOV-2003-0057. Marketing says they commissioned the data. IT says they built the pipeline. Open Campaign_Spend_Monitor.dat.",
    correct: "Correct. IT is the steward of record. The pipeline owner holds accountability.",
    wrong: "Open Campaign_Spend_Monitor.dat and read the Data Steward field.",
  },
  {
    id: 3,
    caseId: "GOV-2003-0063",
    dataset: "Workforce_Shift_Registry.dat",
    fileKey: "workforce_shifts",
    token: "operations",
    leadId: "lead-operations",
    topic: "Unverified steward",
    claimants: [
      { dept: "HR", rep: "A. Lindqvist, CHRO", arg: "The Data Steward field literally names HR Systems Admin. Read the steward field and rule for HR." },
      { dept: "Operations", rep: "M. Dekker, VP Site Operations", arg: "That steward entry is flagged UNVERIFIED — auto-filled. The WMS is our scheduling system and the Governing Function is OPERATIONS." },
    ],
    correctIdx: 1,
    settleFact: "Steward flagged UNVERIFIED — not authoritative. Governing Function OPERATIONS and WMS source decide it.",
    intro: "Case GOV-2003-0063. HR points at the Steward field. Open Workforce_Shift_Registry.dat — is that steward verified?",
    correct: "Correct. An unverified steward cannot settle a dispute. The Governing Function decides it.",
    wrong: "Re-open Workforce_Shift_Registry.dat: an unverified steward is not authoritative.",
  },
  {
    id: 4,
    caseId: "GOV-2003-0079",
    dataset: "Customer_Master_Registry.dat",
    fileKey: "customer_master",
    token: "compliance",
    leadId: "lead-compliance",
    topic: "Regulatory override",
    claimants: [
      { dept: "CRM Team", rep: "P. Mbeki, Head of CRM", arg: "We built the Customer Data Platform. The platform is ours — therefore the data is ours." },
      { dept: "Compliance", rep: "Dr. F. Houten, Chief Compliance Officer / DPO", arg: "This file contains GDPR-regulated personal data. As DPO, I am the mandatory steward of record." },
    ],
    correctIdx: 1,
    settleFact: "GDPR-regulated personal data always falls under Compliance governance.",
    intro: "Case GOV-2003-0079. CRM built the CDP. Compliance claims GDPR. Open Customer_Master_Registry.dat.",
    correct: "Correct. Regulatory obligation overrides operational platform ownership.",
    wrong: "Open Customer_Master_Registry.dat and read Classification and Data Steward.",
  },
];

export const VERIFY: Record<DisputeId, VerifyBlock> = {
  1: {
    title: "FINANCE TOKEN VERIFICATION",
    sub: "Two questions about Revenue_Event_Stream.dat to extract the CFO token.",
    questions: [
      { label: "Which system marks where Finance takes stewardship?", note: "Read the lineage left to right.", opts: ["Order Management System", "Payment Gateway", "Revenue Recognition Engine", "Finance Data Warehouse"], ans: 2, err: "Finance stewardship begins at the Revenue Recognition Engine." },
      { label: "Which system does data pass through LAST before the Finance Data Warehouse?", note: "Find the node immediately before the final destination.", opts: ["Order Management System", "Payment Gateway", "Revenue Recognition Engine", "It goes straight from the OMS"], ans: 2, err: "Look at the node directly before the Finance Data Warehouse." },
    ],
  },
  2: {
    title: "IT TOKEN VERIFICATION",
    sub: "Two questions about Campaign_Spend_Monitor.dat to extract the CTO token.",
    questions: [
      { label: "Who is the named Data Steward?", note: "The Steward field settled this dispute.", opts: ["Head of Digital Marketing", "Digital Infrastructure Team — IT Division", "VP Finance — Revenue Accounting", "IT Security Lead"], ans: 1, err: "Read the Data Steward field in the Inspector." },
      { label: "How many schema fields does the file contain?", note: "Count every field in the schema section.", opts: ["7 fields", "8 fields", "9 fields", "11 fields"], ans: 2, err: "Count every field in the schema section." },
    ],
  },
  3: {
    title: "OPERATIONS TOKEN VERIFICATION",
    sub: "Two questions about Workforce Shift Registry to extract the COO token.",
    questions: [
      { label: "Why can the Steward field NOT settle the dispute?", note: "Read the Steward field — there is a flag.", opts: ["It names the wrong person", "It is flagged UNVERIFIED (auto-filled)", "HR is not a real department", "Steward fields are never used"], ans: 1, err: "There is a status flag beside the steward name." },
      { label: "Compared to Device_Fleet_Telemetry.dat, does Workforce hold MORE, LESS, or THE SAME records?", note: "Compare record counts in each header.", opts: ["MORE records", "LESS records", "THE SAME number"], ans: 1, err: "Compare record counts in both file headers." },
    ],
  },
  4: {
    title: "COMPLIANCE TOKEN VERIFICATION",
    sub: "Two questions about Compliance datasets to extract the CCO token.",
    questions: [
      { label: "What regulation makes Customer_Master_Registry.dat a Compliance dataset?", note: "Read the Classification field.", opts: ["SOX", "HIPAA", "GDPR — General Data Protection Regulation", "ISO 27001"], ans: 2, err: "The Classification field names the regulation explicitly." },
      { label: "Compared to Customer_Master, does Support_Case_Archive hold MORE, LESS, or THE SAME records?", note: "Compare record counts in each header.", opts: ["MORE records", "LESS records", "THE SAME number"], ans: 0, err: "Compare record counts in both Inspector headers." },
    ],
  },
};

export const DECOY_MSG: Record<string, string> = {
  img: "Family vacation photos. Nothing useful here.",
  doc: "Yacht quote from a Swiss broker. $1.4M. Explains Sub-Acct 7.",
  xls: "Personal budget. Overspending on entertainment — routing offshore.",
  pdf: "Cayman property NDA. Connects to the CFO sticky note.",
  mp3: "Stanton voicemail. No audio access — the sticky has what we need.",
};

export const PERSONAL_FILES = [
  { key: "img", name: "vacation_2003.jpg", icon: "🖼" },
  { key: "doc", name: "yacht_quote.doc", icon: "📄" },
  { key: "xls", name: "personal_budget.xls", icon: "📊" },
  { key: "pdf", name: "cayman_nda.pdf", icon: "📕" },
  { key: "mp3", name: "stanton_vm.mp3", icon: "🎵" },
];
